### ISSUE TITLE
Convert all examples to BluePill

### ISSUE THREAD

**Issue by geomatsi** [sajattack/bitbang-hal#14]
Hello @sajattack 

What do you think if I replace Metro-M4 examples by BluePill examples ? BluePill is a much more common board than Metro. So more users will be able to start experimenting right away without additional tinkering with example code.

Regards,
Sergey

**Comment by sajattack** [comment]
Sure.

**Comment by geomatsi** [comment]
Ok. Will do over a couple of weekends and send a PR.

**Comment by geomatsi** [comment]
Resolved by #15
