### ISSUE TITLE
Should we set clock to idle level in SPI::new?

### ISSUE THREAD

**Issue by twitchyliquid64** [sajattack/bitbang-hal#7]
In SPI Mode 2 & 3 (CPOL = 1), the idle level is high.

In the current implementation, if the user does not set the clock to HIGH before calling `SPI::new(...)`, the first bit will be lost.

**Comment by twitchyliquid64** [comment]
This is something of an RFC. I think we should set the clock pin to the idle level for the user. The user of this library should not need to know implementation details like this.

**Comment by sajattack** [comment]
Yeah, makes sense to me.
